### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by dpeet** [dpeet/mbudget#4]
Consider how tags are laid out and whether to add another layer (categories, then tags?)

**Comment by RePeet13** [comment]
Probably want to have both categories and tags
eg. Gas / Fuel Category and Eclipse 2003 tag (you could then have groups of expenses that are related by concepts that aren't tied to where/what the purchase was

**Comment by dpeet** [comment]
Yeah the question then is Gas/Fuel just another tag?  Or does it deserve a definitive separate layer?

For reference, my current system has a name/label for expenses (ie Gas) and then a category (Transportation).  The idea being you can have a graph for names and a graph by category.  

also we need to be careful with tracking our nomenclature (ie what are we referring to by category).  Probably good to add examples in the readme!

**Comment by RePeet13** [comment]
true, we could also look at prior art like Mint to see how they name the stuff

**Comment by dpeet** [comment]
currently (in PR #14 ) I set it up so that a Transaction "category" is references the Budget Item "Name".  Budget Items only have tags, no categories
